version: "3.8"

services:
  go:
    container_name: go-lang
    build:
      context: ./
      dockerfile: builds/go.Dockerfile
    restart: always
    command: tail -F anything
    volumes: 
      - ./code:/go/src